function [pars, lips, pnames, beadnum, eta_ens, gmStruct, muc_hists, h2o_hists, maxE] = Samplewise_Microviscosity(topdir, exptype, vidType)
% This function will look for all of the *Waigh.mat-type files in a directory
% generated by the Process_New_Autoracked_VRPNs() function. It will put out
% a set of 4 figures:
%   1. A paneled figure of subplots of water- and mucus-clustered complex
%   viscosity histograms; one panel for each sample directory
%
%   2. An ensemble mean f-sweep for each sample directory
%
%   3. A kernel density estimate of the probability density function of
%   complex viscosity for each sample directory
%
%   4. A D-alpha plot with ensemble mean for each sample directory
%
% The output variables are as follows for n sample sets:
%   pars - [D,alpha,eta*] nx3 array of ensemble means
%   lips - 100x2 array of the 95% D-alpha confidence ellipse
%   pnames - nx1 cell array of sample directory names
%   beadnum - nx1 vector of m tracked bead counts for each sample
%   eta_ens - struct array of m x frames arrays of the f-sweeps for each bead
%   gmStruct - 1xn struct of Gaussian Mixture Models

cd(topdir)
if (nargin < 2) | isempty(exptype)
    exptype = '**\*Waigh.mat';
end
if (nargin < 3) | isempty(vidType)
    vidType = 'PTMR';
end
filelist = rdir(exptype);

maxt =0;

if strcmp(vidType,'OHSU')
    for i=1:length(filelist)
        foo=load(filelist(i).name);
        [nbds,maxti]=size(foo.eta);
        if maxti>maxt
            maxt = maxti;
        end
    end
else
    foo=load(filelist(1).name);
    [nbds,maxt]=size(foo.eta);
end

if strcmp(vidType,'LONG')
    frmrt = 10;
    wi = 60;
    wrange = 1:250;
elseif strcmp(vidType,'CASA')
    frmrt =1;
    wi = 10;
    wrange = 1:50;
elseif strcmp(vidType,'OHSU')
    frmrt =25;
    wi = 25;
    wrange = 1:50;
else
    frmrt = 60;
    wi = 60;
    wrange = 1:250;
end

tau = 1:maxt;
omega = 1./(tau/frmrt);

nf = length(filelist);
malph = zeros(nf,1);
mDfbm = malph;
meta_ens = malph;
Gppa_all = zeros(nf,length(tau));
mGpEns = Gppa_all;
mGppEns = mGpEns;
wGpEns = mGpEns;
wGppEns = wGpEns;
eta_all = Gppa_all;
eta_bead = eta_all;
eta_ens = struct;
gmStruct = struct();

nsp=numSubplots(nf);
nspr = nsp(1);
nspc = nsp(2);

muc_hists = cell(1,nf);
h2o_hists = muc_hists;

ff=figure;
etaw = 0.9321e-3;
for i=1:nf
    load(filelist(i).name)
    [gRows, gCols] = size(Gppa);
     if gCols<numel(tau)
         nanbuff = numel(tau) - gCols;
         nanbuff = nan(gRows,nanbuff);
         
         eta = [eta,nanbuff];
         Gp = [Gp,nanbuff];
         Gpp = [Gpp,nanbuff];
         Gppa = [Gppa,nanbuff];
     end
    malph(i) = nanmean(eA);
    mDfbm(i) = nanmean(eD);
    Gppa_all(i,:) = 10.^nanmean(log10(Gppa),1);
    etafit = zeros(size(Gppa));
    EtaEns = log10(eta(eta(:,wi)>0,wi));
    EtaEns = EtaEns(((EtaEns>-4)&(EtaEns<4)));
    if ~strcmp(vidType,'CASA')
      gmIter = Fit_two_Gaussian_Mixture(EtaEns,[-3 0.02 -0.5 0.25 0.5],[-3.3 0.005 -2.4 0.005 0; -2.4 0.5 2.0 3.0 1]);
%       gmIter = Fit_two_Gaussian_Mixture(EtaEns,[-3 0.2 -0.5 0.25 0.5],[-3.3 0.005 -2.0 0.005 0; -2.0 0.5 2.0 1.5 1]);% for Cam's paper
%       gmIter = Fit_two_Gaussian_Mixture(EtaEns,[-2.5 0.2 -0.5 0.5 0.5],[-3.3 0.005 -2.0 0.05 0; -1.5 0.5 2.0 0.75 1]);% for Lauren's paper
    else
        gmIter = Fit_two_Gaussian_Mixture(EtaEns,[-2.5 0.1 -1.3 0.1 0.5],[-3.3 0.01 -1.5 0.01 0; -1.5 1.5 -1.0 0.5 1],0,[],0);
    end

    idxIter = cluster(gmIter,EtaEns);
    gmStruct(i).Models = gmIter;
    gmStruct(i).Clusts = idxIter;
        
    pind = strfind(filelist(i).name,'\');
    if numel(pind)>1
        pnames{i} = filelist(i).name(pind(end-1)+1:pind(end)-1);
    else
        pnames{i} = filelist(i).name(1:pind(end)-1);
    end
    
    pnames{i} = strrep(pnames{i},'_',' ');
    gmStruct(i).Names = pnames{i};
    
    muc_hists{i} = EtaEns(idxIter==2);
    h2o_hists{i} = EtaEns(idxIter==1);
    
    subplot(nspr,nspc,i)
    wH = histogram(EtaEns(idxIter==1),'BinWidth',0.1,'linestyle','none','FaceColor',[0.3 0.75 0.93]);
    hold on
    mH = histogram(EtaEns(idxIter==2),'BinWidth',0.1,'linestyle','none','FaceColor',[0.47 0.67 0.19]);
    xlim([-4 2])
    yl = get(gca,'YLim');
    plot([log10(etaw),log10(etaw)],yl,'--k')
    xlabel('log_{10}(\eta*)')
    ylabel('Frequency')
    title(gmStruct(i).Names)
    if i==1
        legend('Water','Mucus')
    end
    
    GpEns = Gp(((EtaEns>-4)&(EtaEns<4)),:);
    GppEns = Gpp(((EtaEns>-4)&(EtaEns<4)),:);
    wGpEns(i,:) = 10.^nanmean(log10(GpEns(idxIter==1,:)),1);
    wGppEns(i,:) = 10.^nanmean(log10(GppEns(idxIter==1,:)),1);
    mGpEns(i,:) = 10.^nanmean(log10(GpEns(idxIter==2,:)),1);
    mGppEns(i,:) = 10.^nanmean(log10(GppEns(idxIter==2,:)),1);
%     if (length(Gppa(:,1)>maxt) && length(Gppa(1,:))==maxt)
%         Gppa=Gppa';
%         Gpp=Gpp';
%         Gp=Gp';
%         Gs=Gs';
%         eta=eta';
%     end
%     for j=1:maxt
%         if j>maxt
%             1;
%         end
%         etafit = Gppa(:,j)./omega;
%     end
    
    eta_all(i,:) = Gppa_all(i,:)./omega;
    eta_bead(i,:) = 10.^nanmean(log10(eta),1);
    pID = ['sample',sprintf('%03d',i)];
%     seta = eta_bead(i,37);
    etall = eta(eta(:,wi)>0,:);
    etall = etall(((EtaEns>-4)&(EtaEns<4)),:);
    eta_ens.(pID) = etall;
end
bolder



figure;
for i=1:nf
    subplot(nspr,nspc,i)
    loglog(omega(wrange),wGpEns(i,wrange),'Color',[0.3 0.75 0.93])
    hold on
    loglog(omega(wrange),wGppEns(i,wrange),'--','Color',[0.3 0.75 0.93])
    loglog(omega(wrange),mGpEns(i,wrange),'Color',[0.47 0.67 0.19])
    loglog(omega(wrange),mGppEns(i,wrange),'--','Color',[0.47 0.67 0.19])
    if i==1
        legend('Water G''','Water G"','Mucus G''','Mucus G"')
    end
    ylim([10^-5 10])
    ylabel('Modulus (Pa)')
    xlabel('Frequency (Hz)')
    title(gmStruct(i).Names)
end 
bolder

if length(omega)<377
    last_f = length(omega);
else
    last_f = 377;
end

figure;
loglog(omega(1:last_f),eta_bead(:,1:last_f))
clist = get(gca,'ColorOrder');
hold on
% for i=0:length(eta_bead(:,1))-1
%     loglog(2*pi*omega,eta_all(i+1,:),'--','color',clist(mod(i,length(clist(:,1)))+1,:))
% end
ylabel('\eta*')
xlabel('\omega (Hz)')
xlim([0.1 100])
ylim(10.^[-4 2])
bolder(24)

% load('macro_compare.mat')
figure;
lfee=length(fieldnames(eta_ens));
beadnum = zeros(lfee,1);
maxPD=zeros(lfee,1);
fcol = get(0,'DefaultAxesColorOrder');
KSDs = zeros(lfee,100);
KSDxs = zeros(lfee,100);
maxE = zeros(lfee,1);
for i=1:lfee
   fn = fieldnames(eta_ens);
   pn = fn{i};
   etaenspw=eta_ens.(pn)(:,wi);
   etaenspw = etaenspw(((etaenspw>1e-6)&(etaenspw<1e4)));
   meta_ens(i) = nanmedian(log10(etaenspw));
   beadnum(i) = length(etaenspw);
   
%    histogram(log10(eta_ens.(pn)(:,wi)),'normalization','probability','BinWidth',0.05,'EdgeColor','none')
    [B, xB] = ksdensity(log10(etaenspw));
    KSDs(i,:)=B;
    KSDxs(i,:)=xB;
    maxE(i) = xB(B==max(B));
    fill(xB,B,fcol(mod(i,7)+1,:))
    xmpd = xB(B==max(B));
    maxPD(i)=xmpd(1);
    alpha(0.5)
   hold on
   yl = get(gca,'Ylim');
%    if i<20
%    mrc = log10(macrorheocomp(i));
%    plot([mrc,mrc],yl)
%    end
   
end
plot([log10(etaw),log10(etaw)],yl,'--k')
xlabel('log_{10}(\eta*)')
ylabel('Probability Density')
title(['\omega=', num2str(omega(wi)),'Hz'])
legend(pnames')
bolder;

if length(filelist)>1
    figure;
    waterfall(KSDxs,repmat([1:lfee],100,1)',KSDs)
    set(gca,'YTick',[1:lfee],'YTickLabel',pnames)
    alpha(0.5)
    xlabel('log_{10}\eta*')
    bolder
end

try
    figure;
    lips = ellipse([malph(~((malph<0.8)&(mDfbm>0.2))),10.^mDfbm(~((malph<0.8)&(mDfbm>0.2)))/4],0.95);
    for i=1:length(mDfbm)
        semilogx((10.^mDfbm(i))/4,malph(i),'.')
        hold on
    end
    semilogx(10.^lips(1,:),lips(2,:))
    ylabel('\alpha')
    xlabel('D_{\alpha}')
    legend('Data','95% CI')
    legend(pnames')
    bolder(24,1,12)
catch eigerr
    lips = [];
end

pars = [(10.^mDfbm)/4,malph,meta_ens];
lips = lips';
pnames=pnames';